# Generated by Django 4.2 on 2023-06-07 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('refrence_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=200, null=True)),
                ('last_name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAdress',
            fields=[
                ('refrence_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('address', models.TextField()),
                ('postal_code', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('recaiver_phonenumbr', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('texprice', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peyment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ispayed', models.BooleanField(default=False)),
                ('total_payed_price', models.CharField(max_length=200, null=True)),
                ('postpay', models.CharField(max_length=200, null=True)),
                ('tatolapaybypost', models.CharField(max_length=200, null=True)),
                ('shippingId', models.IntegerField(null=True)),
                ('shippingType', models.CharField(max_length=200, null=True)),
                ('shippingTypeString', models.CharField(max_length=200, null=True)),
                ('deliveryDate', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('refrence_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=250, null=True)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=250, null=True)),
                ('inventory', models.IntegerField(null=True)),
                ('mainImage', models.URLField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('code', models.CharField(max_length=250, null=True)),
                ('postalCode', models.CharField(max_length=250, null=True)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('status', models.CharField(choices=[('در صف بررسی', 'در صف بررسی'), ('آماده\u200cسازی سفارش', 'آماده\u200cسازی سفارش'), ('تایید سفارش', 'تایید سفارش'), ('خروج از مرکز پردازش', 'خروج از مرکز پردازش'), ('تحویل به پست', 'تحویل به پست'), ('تحویل مرسوله به مشتری', 'تحویل مرسوله به مشتری'), ('مرجوع شده', 'مرجوع شده'), ('بدون وضعیت', 'بدون وضعیت')], default='بدون وضعیت', max_length=50)),
                ('refrence_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('created', models.CharField(max_length=250, null=True)),
                ('userid', models.IntegerField(null=True)),
                ('basketid', models.IntegerField(null=True)),
                ('quntity', models.CharField(max_length=200, null=True)),
                ('bayer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindashbord.buyer')),
                ('mali', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindashbord.peyment')),
                ('products', models.ManyToManyField(to='admindashbord.product')),
            ],
        ),
        migrations.AddField(
            model_name='buyer',
            name='addres',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindashbord.customeradress'),
        ),
    ]
