# Generated by Django 4.2 on 2023-06-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashbord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Networker',
            fields=[
                ('refrence_id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('mobile', models.CharField(max_length=255, null=True)),
                ('fullName', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
