# Generated by Django 4.2 on 2023-06-08 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashbord', '0002_networker'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='networker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admindashbord.networker'),
        ),
    ]
