# Generated by Django 4.2 on 2023-06-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashbord', '0003_order_networker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeradress',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
