# Generated by Django 4.2 on 2023-06-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashbord', '0005_callstatus_order_done_order_call_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='created_main',
            field=models.DateTimeField(null=True),
        ),
    ]
