# Generated by Django 4.2 on 2023-06-18 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindashbord', '0007_mainproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainproduct',
            name='id',
        ),
        migrations.AddField(
            model_name='mainproduct',
            name='refrence_id',
            field=models.BigIntegerField(default=1, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
