# Generated by Django 4.2.2 on 2023-06-20 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindashbord', '0008_remove_mainproduct_id_mainproduct_refrence_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='networker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='net_order', to='admindashbord.networker'),
        ),
    ]
